export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAIL = "SIGN_UP_FAIL"

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAIL = "SIGN_IN_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAIL = "USER_FAIL"

export const SEND_TOKEN_BOARD_SUCCESS = "SEND_TOKEN_BOARD_SUCCESS"
export const SEND_TOKEN_BOARD_FAIL = "SEND_TOKEN_BOARD_FAIL"

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL"
