export const LOAD_BOARD_SUCCESS = "LOAD_BOARD_SUCCESS"
export const LOAD_BOARD_FAIL = "LOAD_BOARD_FAIL"

export const BOARD_PING = "BOARD_PING"

export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL"

export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS"
export const EDIT_LIST_FAIL = "EDIT_LIST_FAIL"

export const REMOVE_LIST_SUCCESS = "REMOVE_LIST_SUCCESS"
export const REMOVE_LIST_FAIL = "REMOVE_LIST_FAIL"

export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS"
export const CREATE_CARD_FAIL = "CREATE_CARD_FAIL"

export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS"
export const EDIT_CARD_FAIL = "EDIT_CARD_FAIL"

export const REMOVE_CARD_SUCCESS = "REMOVE_CARD_SUCCESS"
export const REMOVE_CARD_FAIL = "REMOVE_CARD_FAIL"

export const CHANGE_POS_LIST_SUCCESS = "CHANGE_POS_LIST_SUCCESS"
export const CHANGE_POS_LIST_FAIL = "CHANGE_POS_LIST_FAIL"

export const CHANGE_POS_CARD_SUCCESS = "CHANGE_POS_CARD_SUCCESS"
export const CHANGE_POS_CARD_FAIL = "CHANGE_POS_CARD_FAIL"
