export const LOAD_BOARD_SUCCESS = "LOAD_BOARD_SUCCESS"
export const LOAD_BOARD_FAIL = "LOAD_BOARD_FAIL"

export const BOARD_PING = "BOARD_PING"

export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL"

export const CREATE_LIST_SOCKET = "board:newList"

export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS"
export const EDIT_LIST_FAIL = "EDIT_LIST_FAIL"

export const EDIT_LIST_SOCKET = "board:editList"

export const REMOVE_LIST_SUCCESS = "REMOVE_LIST_SUCCESS"
export const REMOVE_LIST_FAIL = "REMOVE_LIST_FAIL"

export const REMOVE_LIST_SOCKET = "board:removeList"

export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS"
export const CREATE_CARD_FAIL = "CREATE_CARD_FAIL"

export const NEW_CARD_SOCKET = "board:newCard"

export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS"
export const EDIT_CARD_FAIL = "EDIT_CARD_FAIL"

export const EDIT_CARD_SOCKET = "board:editCard"

export const REMOVE_CARD_SUCCESS = "REMOVE_CARD_SUCCESS"
export const REMOVE_CARD_FAIL = "REMOVE_CARD_FAIL"

export const REMOVE_CARD_SOCKET = "board:removeCard"

export const CHANGE_POS_LIST_SUCCESS = "CHANGE_POS_LIST_SUCCESS"
export const CHANGE_POS_LIST_FAIL = "CHANGE_POS_LIST_FAIL"

export const POS_LIST_SOCKET = "board:posList"

export const CHANGE_POS_CARD_SUCCESS = "CHANGE_POS_CARD_SUCCESS"
export const CHANGE_POS_CARD_FAIL = "CHANGE_POS_CARD_FAIL"

export const POS_CARD_SOCKET = "board:posCard"

export const ADD_LABEL_TO_BOARD_SUCCESS = "ADD_LABEL_TO_BOARD_SUCCESS"
export const ADD_LABEL_TO_BOARD_FAIL = "ADD_LABEL_TO_BOARD_FAIL"

export const ADD_LABEL_TO_BOARD_SOCKET = "board:addLabelBoard"

export const EDIT_LABEL_BOARD_SUCCESS = "EDIT_LABEL_BOARD_SUCCESS"
export const EDIT_LABEL_BOARD_FAIL = "EDIT_LABEL_BOARD_FAIL"

export const EDIT_LABEL_BOARD_SOCKET = "board:editLabelBoard"

export const REMOVE_LABEL_FROM_BOARD_SUCCESS = "REMOVE_LABEL_FROM_BOARD_SUCCESS"
export const REMOVE_LABEL_FROM_BOARD_FAIL = "REMOVE_LABEL_FROM_BOARD_FAIL"

export const REMOVE_LABEL_BOARD_SOCKET = "board:removeLabelBoard"

export const ADD_LABEL_TO_CARD_SUCCESS = "ADD_LABEL_TO_CARD_SUCCESS"
export const ADD_LABEL_TO_CARD_FAIL = "ADD_LABEL_TO_CARD_FAIL"

export const ADD_LABEL_CARD_SOCKET = "board:addLabelToCard"

export const REMOVE_LABEL_FROM_CARD_SUCCESS = "REMOVE_LABEL_FROM_CARD_SUCCESS"
export const REMOVE_LABEL_FROM_CARD_FAIL = "REMOVE_LABEL_FROM_CARD_FAIL"

export const REMOVE_LABEL_FROM_CARD_SOCKET = "board:removeLabelCard"

export const SET_BACKGROUND_COLOR_SUCCESS = "SET_BACKGROUND_COLOR_SUCCESS"
export const SET_BACKGROUND_COLOR_FAIL = "SET_BACKGROUND_COLOR_FAIL"

export const SET_BACKGROUND_COLOR_SOCKET = "board:background"

export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS"
export const GET_CARD_FAIL = "GET_CARD_FAIL"
