export const LOAD_BOARDS_SUCCESS = "LOAD_BOARDS_SUCCESS"
export const LOAD_BOARDS_FAIL = "LOAD_BOARDS_FAIL"

export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_FAIL = "CREATE_BOARD_FAIL"

export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS"
export const EDIT_BOARD_FAIL = "EDIT_BOARD_FAIL"

export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS"
export const DELETE_BOARD_FAIL = "DELETE_BOARD_FAIL"
